### ISSUE TITLE
feature request: notify people who aren't in vanish

### ISSUE THREAD

**Issue by TreemanKing** [Bobcat00/AltDetector#3]
For e.g. `altdetector.notify` shows will notify players regardless of their vanish status.

What I'd like is something like `altdetector.notify.notvanished` which will only notify the relevant players with non-vanished players. If further possible, checking the vanish level rank as well in regards to PremiumVanish (soft dependency - not relevant to everyone).

**Comment by TreemanKing** [comment]
No 2. If a vanished player joins and the other player has the permnode of `altdetector.notify.unvanished`, it shouldn't notify them (other than in the logs).

I believe the permnode will provide more flexibility, especially since that some vanish plugins have layered vanish which is particularly helpful between different staff ranks and some people may want the original functionality in combination with the vanish functionality.

**Comment by Bobcat00** [comment]
As a progress update, I have this working with EssentialsX's vanish processing. I also added vanish handling to the `/alt` command with no parameters, as that normally checks all the online players and could reveal the presence of a vanished player.

For permissions, I used `seevanished`, since that seems to be a standard used by other plugins, and the positive logic is easier to understand. There are separate permissions for the join/notify processing and the alt command. If a player has one or both of the following permissions, he can see messages about the vanished player:
- altdetector.notify.seevanished
- altdetector.alt.seevanished

The permissions default to 'op'.

Now I have to see how to integrate this with SuperVanish / PremiumVanish.

**Comment by TreemanKing** [comment]
> Now I have to see how to integrate this with SuperVanish / PremiumVanish. I'm not going to be able to test this. Would you be willing to try it?

Yes. Just attach it to this thread and I can test it.

**Comment by Bobcat00** [comment]
I tested this with SuperVanish and it seems to work. If you could give it a runthru with your setup on PremiumVanish, that would be great.

Keep in mind that notifications about _vanished_ players joining the server won't be sent unless the recipient has the permission `altdetector.notify.seevanished`.

The same applies when using the /alt command _without parameters_, unless the command sender has the permission `altdetector.alt.seevanished`.

And of course this is taking SV/PV's "Layered See And Use Permissions" into account.

[AltDetector-2.03-SNAPSHOT-36509d6.zip](https://github.com/user-attachments/files/15860310/AltDetector-2.03-SNAPSHOT-36509d6.zip)

**Comment by TreemanKing** [comment]
> I tested this with SuperVanish and it seems to work. If you could give it a runthru with your setup on PremiumVanish, that would be great.
> 
> Keep in mind that notifications about _vanished_ players joining the server won't be sent unless the recipient has the permission `altdetector.notify.seevanished`.
> 
> The same applies when using the /alt command _without parameters_, unless the command sender has the permission `altdetector.alt.seevanished`.
> 
> And of course this is taking SV/PV's "Layered See And Use Permissions" into account.
> 
> Double check that you get this in the log file at startup:
> 
> > [AltDetector] PremiumVanish/SuperVanish integration enabled.
> 
> [AltDetector-2.03-SNAPSHOT-36509d6.zip](https://github.com/user-attachments/files/15860310/AltDetector-2.03-SNAPSHOT-36509d6.zip)

Can confirm works. 

Tested all of the above.

**Comment by Bobcat00** [comment]
Great!  Thanks!  I'm going to run it on my server (without SV/PV) for a couple days before releasing it, just to be sure.

**Comment by Bobcat00** [comment]
Closed by commits ff7e8d7c6744afc3c66fdbf00ad443472e294d35 and 36509d69e756394f0aecd31000daf3d994b154dc
